name: Test Setup-Go PR 334 Outputs

on:
  push:
    branches: [ test-605 ]
  workflow_dispatch:

jobs:
  test-setup-go-pr:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout this repo (your code)
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          # cache-dependency-path: |
          #   subdir/go.sum
          #   tools/go.sum
          #   **/*.sum

      - name: Run Go application
        run: go run main.go