name: test-workaround-actions-cache

on:
  # push:
  #   branches: [ test-375-fr ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: '1.25.4'
          cache-dependency-path: |
            go.mod
            .github/cache-buster-${{ github.job }}
      - name: Test Go installation
        run: go version
      - name: Install Dependencies
        run: |
          go mod download

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: '1.25.4'
          cache-dependency-path: |
            go.mod
            .github/cache-buster-${{ github.job }}
      - name: Test Go installation
        run: go version
      - name: Install Dependencies
        run: |
          go mod download