name: Test Setup-Go PR 334 Outputs

on:
  push:
    branches: [ test-375-fr ]
  workflow_dispatch:

jobs:
  test-setup-go-pr:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, windows-latest, windows-11-arm, macos-latest, macos-15-intel, ubuntu-24.04-arm, ubuntu-22.04-arm]
        # runner: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v6
      - name: Clear hosted tool cache
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo rm -rf /opt/hostedtoolcache
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            sudo rm -rf /Users/runner/hostedtoolcache
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell -Command "Remove-Item -Recurse -Force C:\hostedtoolcache"
          fi
      - name: Setup-Go
        # uses: gdams/setup-go@msgo
        uses: actions/setup-go@v6
        with:
          # go-version-file: '.go-version'
          # cache-dependency-path:  'go.sum'
          go-version: '1.25'
          # go-download-base-url: 'https://aka.ms/golang/release/latest'
          # check-latest: true
          cache: false
      - name: Test Go installation
        run: go version