name: Test Setup-Go with main
on:
  push:
    branches: [ test-375-fr ]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
          architecture: 'invalid'
          cache: false

      - name: Install Dependencies
        run: |
          go mod download